// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    internal partial class CppWinRT_AppPass1 : CppWinRT_CodeGenerator<PageDefinition>
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace winrt::");
            this.Write(this.ToStringHelper.ToStringWithCulture(Colonize(ProjectInfo.RootNamespace)));
            this.Write("::implementation\r\n{\r\n    struct XamlMetaDataProvider;\r\n    template <typename D> " +
                    "struct XamlAppMetadataProvider\r\n    {\r\n        using type = XamlMetaDataProvider" +
                    ";\r\n    };\r\n}\r\n\r\nnamespace winrt::");
            this.Write(this.ToStringHelper.ToStringWithCulture(Colonize(Model.CodeInfo.ClassName.Namespace)));
            this.Write("::implementation\r\n{\r\n    template <typename D, typename ... Interfaces>\r\n    stru" +
                    "ct AppT : public ::winrt::");
            this.Write(this.ToStringHelper.ToStringWithCulture(Colonize(Model.CodeInfo.ClassName.Namespace)));
            this.Write("::implementation::App_base<D,\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlMarkup)));
            this.Write("::IXamlMetadataProvider,\r\n        Interfaces...>\r\n    {\r\n        using base_type " +
                    "= typename AppT::base_type;\r\n        using base_type::base_type;\r\n        using " +
                    "XamlMetaDataProvider = typename ::winrt::");
            this.Write(this.ToStringHelper.ToStringWithCulture(Colonize(ProjectInfo.RootNamespace)));
            this.Write("::implementation::XamlAppMetadataProvider<D>::type;\r\n        using IXamlType = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlMarkup)));
            this.Write("::IXamlType;\r\n\r\n        AppT();\r\n        ~AppT();\r\n        void InitializeCompone" +
                    "nt();\r\n\r\n");
  if(!ProjectInfo.GenerateProviderCode) { 
            this.Write("        void AddOtherProvider(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlMarkup)));
            this.Write("::IXamlMetadataProvider const& otherProvider);\r\n");
  }
            this.Write("        IXamlType GetXamlType(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.WindowsXamlInterop)));
            this.Write("::TypeName const& type);\r\n        IXamlType GetXamlType(::winrt::hstring const& f" +
                    "ullName);\r\n        ::winrt::com_array<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlMarkup)));
            this.Write("::XmlnsDefinition> GetXmlnsDefinitions();\r\n\r\n    private:\r\n        bool _contentL" +
                    "oaded{false};\r\n        winrt::com_ptr<XamlMetaDataProvider> _appProvider;\r\n     " +
                    "   winrt::com_ptr<XamlMetaDataProvider> AppProvider();\r\n    };\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
