// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    internal partial class CppWinRT_BindingInfoPass1 : CppWinRT_CodeGenerator<BindingInfoDefinition>
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winrt::");
            this.Write(this.ToStringHelper.ToStringWithCulture(Colonize(ProjectInfo.RootNamespace)));
            this.Write("::implementation\r\n{\r\n    using DataContextChangedEventArgs = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.Xaml)));
            this.Write("::DataContextChangedEventArgs;\r\n    using DependencyObject = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.Xaml)));
            this.Write("::DependencyObject;\r\n    using DependencyProperty = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.Xaml)));
            this.Write("::DependencyProperty;\r\n    using FrameworkElement = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.Xaml)));
            this.Write("::FrameworkElement;\r\n    using IInspectable = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.WindowsFoundation)));
            this.Write("::IInspectable;\r\n    using INotifyCollectionChanged = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlInterop)));
            this.Write("::INotifyCollectionChanged;\r\n    using INotifyPropertyChanged = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlData)));
            this.Write("::INotifyPropertyChanged;\r\n    using PropertyChangedEventArgs = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlData)));
            this.Write("::PropertyChangedEventArgs;\r\n    using NotifyCollectionChangedEventArgs = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlInterop)));
            this.Write("::NotifyCollectionChangedEventArgs;\r\n    using ContainerContentChangingEventArgs " +
                    "= ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlControls)));
            this.Write("::ContainerContentChangingEventArgs;\r\n    using IComponentConnector = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlMarkup)));
            this.Write("::IComponentConnector;\r\n    using WindowActivatedEventArgs = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.Xaml)));
            this.Write("::WindowActivatedEventArgs;\r\n");
 if (ProjectInfo.IsInputValidationEnabled) {
            this.Write("    using INotifyDataErrorInfo = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlData)));
            this.Write("::INotifyDataErrorInfo;\r\n    using DataErrorsChangedEventArgs = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlData)));
            this.Write("::DataErrorsChangedEventArgs;\r\n");
 }
            this.Write(@"
    struct XamlBindings;

    struct IXamlBindings
    {
        virtual ~IXamlBindings() {}
        virtual bool IsInitialized() = 0;
        virtual void Update() = 0;
        virtual bool SetDataRoot(IInspectable const& data) = 0;
        virtual void StopTracking() = 0;
        virtual void Connect(int connectionId, IInspectable const& target) = 0;
        virtual void Recycle() = 0;
        virtual void ProcessBindings(IInspectable const& item, int itemIndex, int phase, std::int32_t& nextPhase) = 0;
        virtual void SubscribeForDataContextChanged(FrameworkElement const& object, XamlBindings& handler) = 0;
        virtual void DisconnectUnloadedObject(int connectionId) = 0;
    };

    struct IXamlBindingTracking
    {
        virtual void PropertyChanged(IInspectable const& sender, PropertyChangedEventArgs const& e) = 0;
        virtual void CollectionChanged(IInspectable const& sender, NotifyCollectionChangedEventArgs const& e) = 0;
        virtual void DependencyPropertyChanged(DependencyObject const& sender, DependencyProperty const& prop) = 0;
        virtual void VectorChanged(IInspectable const& sender, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.WindowsFoundationCollections)));
            this.Write("::IVectorChangedEventArgs const& e) = 0;\r\n        virtual void MapChanged(IInspec" +
                    "table const& sender, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.WindowsFoundationCollections)));
            this.Write("::IMapChangedEventArgs<::winrt::hstring> const& e) = 0;\r\n");
 if (ProjectInfo.IsInputValidationEnabled) {
            this.Write("        virtual void ErrorsChanged(IInspectable const& sender, DataErrorsChangedE" +
                    "ventArgs const& e) = 0;\r\n");
 } 
            this.Write("    };\r\n\r\n    struct XamlBindings : public winrt::implements<XamlBindings,\r\n     " +
                    "   ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.Xaml)));
            this.Write("::IDataTemplateExtension,\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlMarkup)));
            this.Write("::IComponentConnector,\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlMarkup)));
            this.Write("::IDataTemplateComponent>\r\n    {\r\n        XamlBindings(std::shared_ptr<IXamlBindi" +
                    "ngs>&& pBindings);\r\n\r\n        void Connect(int connectionId, IInspectable const&" +
                    " target);\r\n        IComponentConnector GetBindingConnector(std::int32_t, IInspec" +
                    "table const&);\r\n        virtual void ProcessBindings(IInspectable const& item, i" +
                    "nt itemIndex, int phase, std::int32_t& nextPhase);\r\n        virtual void Recycle" +
                    "();\r\n        bool ProcessBinding(std::uint32_t phase);\r\n        int ProcessBindi" +
                    "ngs(ContainerContentChangingEventArgs const& args);\r\n        void ResetTemplate(" +
                    ");\r\n        void Initialize();\r\n        void Update();\r\n        void StopTrackin" +
                    "g();\r\n        void Loading(FrameworkElement const& src, IInspectable const& data" +
                    ");\r\n        void Activated(IInspectable const& sender, WindowActivatedEventArgs " +
                    "const& args);\r\n        void DataContextChanged(FrameworkElement const& sender, D" +
                    "ataContextChangedEventArgs const& args);\r\n        void SubscribeForDataContextCh" +
                    "anged(FrameworkElement const& object);\r\n        virtual void DisconnectUnloadedO" +
                    "bject(int connectionId);\r\n\r\n    private:\r\n        std::shared_ptr<IXamlBindings>" +
                    " _pBindings;\r\n    };\r\n\r\n    template <typename TBindingsTracking>\r\n    struct Xa" +
                    "mlBindingsBase : public IXamlBindings\r\n    {\r\n    protected:\r\n        bool _isIn" +
                    "itialized = false;\r\n        std::shared_ptr<TBindingsTracking> _bindingsTracking" +
                    ";\r\n        winrt::event_token _dataContextChangedToken {};\r\n        static const" +
                    " int NOT_PHASED = (1 << 31);\r\n        static const int DATA_CHANGED = (1 << 30);" +
                    "\r\n\r\n        XamlBindingsBase() = default;\r\n        virtual ~XamlBindingsBase()\r\n" +
                    "        {\r\n            if (_bindingsTracking)\r\n            {\r\n                _b" +
                    "indingsTracking->SetListener(nullptr);\r\n                _bindingsTracking.reset(" +
                    ");\r\n            }\r\n        }\r\n\r\n        virtual void ReleaseAllListeners() {}\r\n\r" +
                    "\n    public:\r\n        void InitializeTracking(IXamlBindingTracking* pBindingsTra" +
                    "cking)\r\n        {\r\n            _bindingsTracking = std::make_shared<TBindingsTra" +
                    "cking>();\r\n            _bindingsTracking->SetListener(pBindingsTracking);\r\n     " +
                    "   }\r\n\r\n        virtual void StopTracking() override\r\n        {\r\n            Rel" +
                    "easeAllListeners();\r\n            this->_isInitialized = false;\r\n        }\r\n\r\n   " +
                    "     virtual bool IsInitialized() override\r\n        {\r\n            return this->" +
                    "_isInitialized;\r\n        }\r\n\r\n        void SubscribeForDataContextChanged(Framew" +
                    "orkElement const& object, XamlBindings& handler) override\r\n        {\r\n          " +
                    "  this->_dataContextChangedToken = object.DataContextChanged({ &handler, &XamlBi" +
                    "ndings::DataContextChanged });\r\n        }\r\n\r\n        virtual void Recycle() over" +
                    "ride {}\r\n\r\n        virtual void ProcessBindings(IInspectable const&, int, int, s" +
                    "td::int32_t& nextPhase) override\r\n        {\r\n            nextPhase = -1;\r\n      " +
                    "  }\r\n    };\r\n\r\n    struct XamlBindingTrackingBase\r\n    {\r\n        XamlBindingTra" +
                    "ckingBase();\r\n        void SetListener(IXamlBindingTracking* pBindings);\r\n      " +
                    "  void PropertyChanged(IInspectable const& sender, PropertyChangedEventArgs cons" +
                    "t& e);\r\n        void CollectionChanged(IInspectable const& sender, NotifyCollect" +
                    "ionChangedEventArgs const& e);\r\n        void DependencyPropertyChanged(Dependenc" +
                    "yObject const& sender, DependencyProperty const& prop);\r\n        void VectorChan" +
                    "ged(IInspectable const& sender, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.WindowsFoundationCollections)));
            this.Write("::IVectorChangedEventArgs const& e);\r\n        void MapChanged(IInspectable const&" +
                    " sender, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.WindowsFoundationCollections)));
            this.Write("::IMapChangedEventArgs<::winrt::hstring> const& e);\r\n");
 if (ProjectInfo.IsInputValidationEnabled) {
            this.Write("        void ErrorsChanged(IInspectable const& sender, DataErrorsChangedEventArgs" +
                    " const& e);\r\n");
 } 
            this.Write("        void UpdatePropertyChangedListener(INotifyPropertyChanged const& obj, INo" +
                    "tifyPropertyChanged& cache, ::winrt::event_token& token);\r\n        void UpdatePr" +
                    "opertyChangedListener(INotifyPropertyChanged const& obj, ::winrt::weak_ref<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlData)));
            this.Write(@"::INotifyPropertyChanged>& cache, ::winrt::event_token& token);
        void UpdateCollectionChangedListener(INotifyCollectionChanged const& obj, INotifyCollectionChanged& cache, ::winrt::event_token& token);
        void UpdateDependencyPropertyChangedListener(DependencyObject const& obj, DependencyProperty const& property, DependencyObject& cache, std::int64_t& token);
        void UpdateDependencyPropertyChangedListener(DependencyObject const& obj, DependencyProperty const& property, ::winrt::weak_ref<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.Xaml)));
            this.Write("::DependencyObject>& cache, std::int64_t& token);\r\n");
 if (ProjectInfo.IsInputValidationEnabled) {
            this.Write("        void UpdateErrorsChangedListener(INotifyDataErrorInfo const& obj, INotify" +
                    "DataErrorInfo& cache, ::winrt::event_token& token);\r\n        void UpdateErrorsCh" +
                    "angedListener(INotifyDataErrorInfo const& obj, ::winrt::weak_ref<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Projection(KnownNamespaces.XamlData)));
            this.Write("::INotifyDataErrorInfo>& cache, ::winrt::event_token& token);\r\n");
 } 
            this.Write("\r\n    private:\r\n        IXamlBindingTracking* _pBindingsTrackingWeakRef{nullptr};" +
                    "\r\n    };\r\n\r\n    template <typename T>\r\n    struct ResolveHelper\r\n    {\r\n        " +
                    "static T Resolve(::winrt::weak_ref<T> const& wr)\r\n        {\r\n            return " +
                    "wr.get();\r\n        }\r\n    };\r\n\r\n    template<>\r\n    struct ResolveHelper<::winrt" +
                    "::hstring>\r\n    {\r\n        using ResolveType = ::winrt::Windows::Foundation::IRe" +
                    "ference<::winrt::hstring>;\r\n        static ::winrt::hstring Resolve(::winrt::wea" +
                    "k_ref<ResolveType> const& wr)\r\n        {\r\n            return wr.get().Value();\r\n" +
                    "        }\r\n    };\r\n\r\n    template<typename T, typename TBindingsTracking>\r\n    s" +
                    "truct ReferenceTypeXamlBindings : public XamlBindingsBase<TBindingsTracking>\r\n  " +
                    "  {\r\n    protected:\r\n        ReferenceTypeXamlBindings() {}\r\n        virtual voi" +
                    "d Update_(T, int) {}\r\n\r\n    public:\r\n        T GetDataRoot()\r\n        {\r\n       " +
                    "     return ResolveHelper<T>::Resolve(this->_dataRoot);\r\n        }\r\n\r\n        bo" +
                    "ol SetDataRoot(IInspectable const& data) override\r\n        {\r\n            if (da" +
                    "ta)\r\n            {\r\n                this->_dataRoot = ::winrt::unbox_value<T>(da" +
                    "ta);\r\n                return true;\r\n            }\r\n            return false;\r\n  " +
                    "      }\r\n\r\n        virtual void Update() override\r\n        {\r\n            this->" +
                    "Update_(this->GetDataRoot(), this->NOT_PHASED);\r\n            this->_isInitialize" +
                    "d = true;\r\n        }\r\n\r\n    private:\r\n        ::winrt::weak_ref<T> _dataRoot;\r\n " +
                    "   };\r\n\r\n    template<typename T, typename TBindingsTracking>\r\n    struct ValueT" +
                    "ypeXamlBindings : public XamlBindingsBase<TBindingsTracking>\r\n    {\r\n    protect" +
                    "ed:\r\n        ValueTypeXamlBindings() {}\r\n        virtual void Update_(T, int) {}" +
                    "\r\n\r\n    public:\r\n        T GetDataRoot()\r\n        {\r\n            return this->_d" +
                    "ataRoot;\r\n        }\r\n\r\n        bool SetDataRoot(IInspectable const& data) overri" +
                    "de\r\n        {\r\n            if (data)\r\n            {\r\n                this->_data" +
                    "Root = ::winrt::unbox_value<T>(data);\r\n                return true;\r\n           " +
                    " }\r\n            return false;\r\n        }\r\n\r\n        virtual void Update() overri" +
                    "de\r\n        {\r\n            this->Update_(this->GetDataRoot(), this->NOT_PHASED);" +
                    "\r\n            this->_isInitialized = true;\r\n        }\r\n\r\n    private:\r\n        T" +
                    " _dataRoot;\r\n    };\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
